backend:
  name: github
  repo: aaroncuddeback/GatsbyJSBlog #replace with your username/repo

media_folder: static/assets

collections:
  - name: post
    label: Post
    slug: index
    folder: content/posts/
    create: true
    fields:
      - { name: title, label: Title }
      - { name: subTitle, label: subTitle }
      - { name: category, label: Category }
      - { name: cover, label: Cover, widget: image }
      - { name: body, label: Body, widget: markdown }
# This line should *not* be indented
# publish_mode: editorial_workflow
